# Generated by Django 4.2 on 2024-07-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_photo_alter_product_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('salad', 'Salad'), ('soup', 'Soup')], max_length=50),
        ),
    ]
